# Generated by Django 5.0.1 on 2024-01-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='static/image/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
