# Generated by Django 5.0.1 on 2024-01-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpic', '0002_image_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
