# Generated by Django 5.0.1 on 2024-01-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpic', '0003_alter_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='result_images/')),
            ],
        ),
    ]
