# Generated by Django 5.0.1 on 2024-01-26 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpic', '0004_resultimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detect_name',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
