# Generated by Django 5.0.1 on 2024-01-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpic', '0005_image_detect_name_alter_image_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='detect_name',
        ),
        migrations.AddField(
            model_name='resultimage',
            name='detect_name',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
