# Generated by Django 5.0.1 on 2024-01-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodpic', '0006_remove_image_detect_name_resultimage_detect_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='path',
            new_name='image',
        ),
    ]
