# Generated by Django 5.0.1 on 2024-01-26 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpic', '0007_rename_path_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultimage',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
