# Generated by Django 5.0.1 on 2024-01-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=32, verbose_name='product_name')),
                ('price', models.IntegerField(verbose_name='product_price')),
                ('description', models.TextField(verbose_name='product_description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='product_image')),
                ('stock', models.IntegerField(verbose_name='product_stock')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='product_register_date')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'db_table': 'product_table',
            },
        ),
    ]
