# Generated by Django 5.0.1 on 2024-01-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='register_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='colDay',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colPath',
            field=models.FileField(blank=True, upload_to='Uploaded Files/%y/%m/%d/'),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
