# Generated by Django 5.0.1 on 2024-01-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUp', '0002_alter_product_options_remove_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgeupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, upload_to='about_me/awards/&Y/%m/%d')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
